services:
  workspace:
    container_name: php_workspace
    build:
      context: ./workspace
    tty: true
    volumes:
      - ../:/ntfy-php-library
      - vendor:/ntfy-php-library/vendor
    working_dir: /ntfy-php-library
    environment:
      - NTFY_URI=${NTFY_URI}
      - HTTPBIN_URI=${HTTPBIN_URI}
      - XDEBUG_MODE=coverage

  ntfy:
    container_name: ntfy
    image: binwiederhier/ntfy:v2.28.0@sha256:6ef4b819f722fccdc036af611c4774cfdc2de821ab74fdd48bbf4c9d6f8973da
    command: serve
    volumes:
     - '../.ci/ntfy/server.yml:/etc/ntfy/server.yml'
    ports:
      - "127.0.0.1:8080:80"

  httpbin:
    container_name: httpbin
    image: mccutchen/go-httpbin:2.24.0@sha256:c0bf25bcde7329ba1d07aa372bc1f6ad33608ab1a8b40870769b9d99aa466c5c
    ports:
      - "127.0.0.1:8081:8080"

volumes:
  vendor:
