services:
  workspace:
    container_name: php_workspace
    build:
      context: ./workspace
    tty: true
    volumes:
      - ../:/ntfy-php-library
      - vendor:/ntfy-php-library/vendor
    working_dir: /ntfy-php-library
    environment:
      - NTFY_URI=${NTFY_URI}
      - HTTPBIN_URI=${HTTPBIN_URI}
      - XDEBUG_MODE=coverage

  ntfy:
    container_name: ntfy
    image: binwiederhier/ntfy:v2.25.0@sha256:cfbbb1bac9196cb711e29ef0ac4adaeb033be6235f1df857705dc39c14384a1d
    command: serve
    volumes:
     - '../.ci/ntfy/server.yml:/etc/ntfy/server.yml'
    ports:
      - "127.0.0.1:8080:80"

  httpbin:
    container_name: httpbin
    image: mccutchen/go-httpbin:2.23.1@sha256:90ac1702685468aa592938e65b2ba1b4757e0c006934a962ef7271a8717aaa3b
    ports:
      - "127.0.0.1:8081:8080"

volumes:
  vendor:
